DCP-3398 : Updating distribution/README.txt as it is what is put in the zip
enasequence/ena-ftp-downloader pull request #54
Opened 2022-10-28 15:45 UTC by swatisuman1990

2022-10-31 15:39 UTC, suranjayathilaka requested changes
make sure everything that was in the removed readme is not missing in the top level readme

2022-10-31 15:52 UTC, swatisuman1990 commented
> make sure everything that was in the removed readme is not missing in the top level readme

The ReadMe in distribution was an old version of the Project level ReadMe. The current one is just an updated version.

2022-10-31 15:57 UTC, suranjayathilaka commented on distribution/README.txt
> -For support/issues, please contact us at https://www.ebi.ac.uk/ena/browser/support
what about all this ?

2022-10-31 15:57 UTC, suranjayathilaka commented on distribution/README.txt
> -Privacy Notice
and this?

2022-11-01 13:25 UTC, suranjayathilaka approved these changes

2022-11-01 13:25 UTC, merged